services:
  webapp:
    build:
      context: ./docker/base
      tags:
        - "csc418:latest"
    image: csc418:latest
    ports:
      - "9090:3333"
      - "3000:3000"
      - "4200:4200"
      - "8088:8088"
      - "8000:8000"
    volumes:
      - ./docs:/data # temporary
      - ../courses:/lectures # courses is a github repo containing lecture materials
      - ../csc418data:/apps # csc418data is a github repo (could be private or public) containing relevant data and example codes
    
  webdb: # back-end MongoDB container
    build:
      context: ./docker/webdb
      tags:
        - "csc418db:base"
    image: csc418db:base
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=goldenrams
    ports:
      - "27017:27017"
    volumes:
       - ./mongo_data:/data/db
       
networks:
  default:
    driver: bridge

